classproject/classproject/urls.py
from django.contrib import admin
from django.urls import path,include
from project import views

urlpatterns = [
    path('project/',include('project.urls')),
    path('admin/', admin.site.urls),
    path('createpost/',views.createpost)
]

classproject/project/urls.py
from django.urls import path
from . import views
app_name='project'


urlpatterns = [
    path('',views.index,name='index'),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    path('portfolio/',views.portfolio,name='portfolio'),

]

classproject/project/models.py
from django.db import models


# Create your models here.

class Achievments(models.Model):
    photos = models.IntegerField()
    customers = models.IntegerField()
    photographs = models.IntegerField()

    
class Testimonial(models.Model):
    description = models.CharField(max_length=10380)  
    
    def __str__(self):
        return self.description

class Form(models.Model):
    Name = models.CharField(max_length=55)
    Phone_no = models.IntegerField()
    Email = models.CharField(max_length=100)
    Message = models.CharField(max_length=1000)  


    def __str__(self):
        return self.Name

classproject/project/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Achievments,Testimonial,Form

# Create your views here.

def index(request):
    values=Achievments.objects.all()
    des = Testimonial.objects.all()
    len = Testimonial.objects.all().count()
    context={'values' : values,'des' : des, 'len': len}
    return render(request,'index.html',context)


def createpost(request):
        if request.method == 'POST':
            if request.POST.get('name') and request.POST.get('email') and request.POST.get('phone') and request.POST.get('message'):
                post=Form()
                post.Name= request.POST.get('name')
                post.Email= request.POST.get('email')
                post.Message= request.POST.get('message')
                post.Phone_no= request.POST.get('phone')
                post.save()
                
                return render(request, 'contact.html')  

        else:
                return render(request,'contact.html')      


def about(request):
    return render(request,'about.html')   


def contact(request):
    return render(request,'contact.html') 


def portfolio(request):
    return render(request,'portfolio.html')    

classproject/project/templates/about.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Uliya</title>


  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />
</head>

<body class="sub_page">

  <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-11 offset-lg-1">
            <nav class="navbar navbar-expand-lg custom_nav-container ">
              <a class="navbar-brand" href="{% url 'project:index' %}">
                <img src="{% static 'images/logo.png' %}" alt="">
                <span>
                  Uliya
                </span>
              </a>
              </a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="d-flex ml-auto flex-column flex-lg-row align-items-center">
                  <ul class="navbar-nav  ">
                    <li class="nav-item ">
                      <a class="nav-link" href="{% url 'project:index' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'project:about' %}"> About</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'project:portfolio' %}"> Portfolio </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'project:contact' %}">Contact Us</a>
                    </li>
                  </ul>
                  <form class="form-inline">
                    <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit"></button>
                  </form>
                </div>

              </div>
            </nav>
          </div>
        </div>
      </div>
    </header>
    <!-- end header section -->
  </div>

  <!-- about section -->

  <section class="about_section layout_padding">
    <div class="container">
      <div class="heading_container">
        <h2>
          About Studio
        </h2>
      </div>
      <div class="box">
        <div class="img-box">
          <img src="{% static 'images/about-img.jpg' %}" alt="">
          <div class="about_img-bg">
            <img src="{% static 'images/about-img-bg.png' %}" alt="">
          </div>
        </div>
        <div class="detail-box">
          <p>
            It is a long established fact that a reader will be distracted by the readable content of a page when
            looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of
            letters,
          </p>
          <div>
            <a href="">
              about More
            </a>
          </div>
        </div>
      </div>
    </div>

  </section>

  <!-- end about section -->


  <!-- info section -->
  <section class="info_section ">
    <div class="container">
      <div class="info_container">
        <div class="info_social">
          <div class="d-flex justify-content-center">
            <h4 class="">
              Follow on
            </h4>
          </div>
          <div class="social_box">
            <a href="">
              <img src="{% static 'images/fb.png' %}" alt="">
            </a>
            <a href="">
              <img src="{% static 'images/twitter.png' %}" alt="">
            </a>
            <a href="">
              <img src="{% static 'images/instagram.png' %}" alt="">
            </a>
            <a href="">
              <img src="{% static 'images/linkedin.png' %}" alt="">
            </a>
            <a href="">
              <img src="{% static 'images/dribble.png' %}" alt="">
            </a>
            <a href="">
              <img src="{% static 'images/pinterest.png' %}" alt="">
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end info_section -->

  <!-- footer section -->
  <section class="container-fluid footer_section">
    <div class="container">
      <p>
        &copy; 2019 All Rights Reserved By
        <a href="https://html.design/">Free Html Templates</a>
      </p>
    </div>
  </section>
  <!-- footer section -->

  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>

</body>

</html>

classproject/project/templates/contact.html
{%load static %}
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Uliya</title>


  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />
</head>

<body class="sub_page">

  <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-11 offset-lg-1">
            <nav class="navbar navbar-expand-lg custom_nav-container ">
              <a class="navbar-brand" href="{% url 'project:index' %}">
                <img src="{% static 'images/logo.png' %}" alt="">
                <span>
                  Uliya
                </span>
              </a>
              </a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="d-flex ml-auto flex-column flex-lg-row align-items-center">
                  <ul class="navbar-nav  ">
                    <li class="nav-item ">
                      <a class="nav-link" href="{% url 'project:index' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'project:about' %}"> About</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'project:portfolio' %}"> Portfolio </a>
                    </li>
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'project:contact' %}">Contact Us</a>
                    </li>
                  </ul>
                  <form class="form-inline">
                    <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit"></button>
                  </form>
                </div>

              </div>
            </nav>
          </div>
        </div>
      </div>
    </header>
    <!-- end header section -->
  </div>

  <!-- contact section -->

  <section class="contact_section layout_padding">
    <div class="bg-img1">
      <img src="{% static 'images/bg-img-1.png' %}" alt="">
    </div>
    <div class="bg-img2">
      <img src="{% static 'images/bg-img-2.png' %}" alt="">
    </div>
    <div class="container">
      <div class="heading_container">
        <h2>
          Contact Us
        </h2>
      </div>
      <div class="">
        <div class="row">
          <div class="col-md-8 mx-auto">
            <form action="/createpost/ " method='POST'>
              {% csrf_token %}
              <div class="contact_form-container">
                <div>
                  <div>
                    
                    <input type="text" placeholder="Name" name="name">
                  </div>
                  <div>
                    <input type="text" placeholder="Phone Number" name="phone">
                  </div>
                  <div>
                    <input type="email" placeholder="Email" name= "email">
                  </div>
                  <div class="">
                    <input type="text" placeholder="Message" class="message_input" name="message">
                  </div>
                  <div class=" d-flex justify-content-center ">
                    <button type="submit">
                      Send
                    </button>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>


  <!-- end contact section -->


  <!-- info section -->
  <section class="info_section ">
    <div class="container">
      <div class="info_container">
        <div class="info_social">
          <div class="d-flex justify-content-center">
            <h4 class="">
              Follow on
            </h4>
          </div>
          <div class="social_box">
            <a href="">
              <img src="{% static 'images/fb.png' %}" alt="">
            </a>
            <a href="">
              <img src="{% static 'images/twitter.png' %}" alt="">
            </a>
            <a href="">
              <img src="{% static 'images/instagram.png' %}" alt="">
            </a>
            <a href="">
              <img src="{% static 'images/linkedin.png' %}" alt="">
            </a>
            <a href="">
              <img src="{% static 'images/dribble.png' %}" alt="">
            </a>
            <a href="">
              <img src="{% static 'images/pinterest.png' %}" alt="">
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end info_section -->

  <!-- footer section -->
  <section class="container-fluid footer_section">
    <div class="container">
      <p>
        &copy; 2019 All Rights Reserved By
        <a href="https://html.design/">Free Html Templates</a>
      </p>
    </div>
  </section>
  <!-- footer section -->

  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>

</body>

</html>

classproject/project/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Uliya</title>


  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />
</head>

<body>

  <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-11 offset-lg-1">
            <nav class="navbar navbar-expand-lg custom_nav-container ">
              <a class="navbar-brand" href="{% url 'project:index' %}">
                <img src="{% static 'images/logo.png' %}" alt="">
                <span>
                  Uliya
                </span>
              </a>
              </a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="d-flex ml-auto flex-column flex-lg-row align-items-center">
                  <ul class="navbar-nav  ">
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'project:index' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'project:about' %}"> About</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'project:portfolio' %}"> Portfolio </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'project:contact' %}">Contact Us</a>
                    </li>
                  </ul>
                  <form class="form-inline">
                    <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit"></button>
                  </form>
                </div>

              </div>
            </nav>
          </div>
        </div>
      </div>
    </header>
    <!-- end header section -->
    <!-- slider section -->
    <section class=" slider_section position-relative">
      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="container-fluid">
              <div class="row">
                <div class="col-md-5 offset-md-1 ">
                  <div class="detail_box">
                    <h1>
                      photography <br>
                      studio
                    </h1>
                    <p>
                      It is a long established fact that a reader will be distracted by the readable content
                    </p>
                    <div class="btn-box">
                      <a href="" class="btn-1">
                        About Us
                      </a>
                      <a href="" class="btn-2">
                        Get A Quote
                      </a>
                    </div>
                  </div>
                </div>
                <div class="col-md-6 px-0">
                  <div class="img-box">
                    <img src="{% static 'images/slider-img.jpg' %}" alt="">
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <div class="container-fluid">
              <div class="row">
                <div class="col-md-5 offset-md-1">
                  <div class="detail_box">
                    <h1>
                      photography <br>
                      studio
                    </h1>
                    <p>
                      It is a long established fact that a reader will be distracted by the readable content
                    </p>
                    <div class="btn-box">
                      <a href="" class="btn-1">
                        About Us
                      </a>
                      <a href="" class="btn-2">
                        Get A Quote
                      </a>
                    </div>
                  </div>
                </div>
                <div class="col-md-6 px-0">
                  <div class="img-box">
                    <img src="{% static 'images/slider-img.jpg' %}" alt="">
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <div class="container-fluid">
              <div class="row">
                <div class="col-md-5 offset-md-1">
                  <div class="detail_box">
                    <h1>
                      photography <br>
                      studio
                    </h1>
                    <p>
                      It is a long established fact that a reader will be distracted by the readable content
                    </p>
                    <div class="btn-box">
                      <a href="" class="btn-1">
                        About Us
                      </a>
                      <a href="" class="btn-2">
                        Get A Quote
                      </a>
                    </div>
                  </div>
                </div>
                <div class="col-md-6 px-0">
                  <div class="img-box">
                    <img src="{% static 'images/slider-img.jpg' %}" alt="">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="carousel_btn-container">
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>

    </section>
    <!-- end slider section -->
  </div>

  <!-- achieve section -->

  <section class="achieve_section layout_padding">
    <div class="container">
      <div class="heading_container">
        <h2>
          ACHIEVEMENTS
        </h2>
        <p>
          minim veniam, quis nostrud exercitation ullamco laboris nisi
        </p>
      </div>
      <div class="achieve_container">
        <div class="box">
          <div class="img-box">
            <img src="{% static 'images/a-1.png' %}" alt="">
          </div>
          <div class="detail-box">
            <h2>
              {% for val in values %}
                {{ val.photos }}+
              {% endfor %}  
            </h2>
            <h6>
              Photo Session
            </h6>
          </div>
        </div>
        <div class="box">
          <div class="img-box">
            <img src="{% static 'images/a-2.png' %}" alt="">
          </div>
          <div class="detail-box">
            <h2>
              {% for val in values %}
                {{ val.customers }}+
              {% endfor %}
            </h2>
            <h6>
              Happy Customers
            </h6>
          </div>
        </div>
        <div class="box">
          <div class="img-box">
            <img src="{% static 'images/a-3.png' %}" alt="">
          </div>
          <div class="detail-box">
            <h2>
              {% for val in values %}
                {{ val.photographs }}+
              {% endfor %}
            </h2>
            <h6>
              Archive Photographs
            </h6>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end achieve section -->

  <!-- client section -->

  <section class="client_section layout_padding-bottom">
    <div class="container">
      <div class="heading_container">
        <h2>
          Testimonial
        </h2>
        
        <p>
          minim veniam, quis nostrud exercitation ullamco laboris nisi
        </p>
      </div>
      <div class="layout_padding2-top">
        <div id="carouselExample2Controls" class="carousel slide" data-ride="carousel">
          <div class="row">
            <div class="col-md-3">
              <div class="btn_container">
                <a class="carousel-control-prev" href="#carouselExample2Controls" role="button" data-slide="prev">
                  <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExample2Controls" role="button" data-slide="next">
                  <span class="sr-only">Next</span>
                </a>
              </div>
            </div>
            <div class="col-md-9 col-lg-8">
              
              <div class="carousel-inner">
                {% for d in des %}
                
                <div class="carousel-item{% if forloop.counter == len %} active{% endif %}" id="slide">
                  <div class="detail-box">
                    <h4>
                      Aloz den
                    </h4>
                  
                    <p>
                      {{ d.description }}
                    </p>
                   
                  </div>
                </div>

                
                {% endfor %} 
              </div>
            </div>

          </div>

        </div>
      </div>
    </div>
  </section>


  <!-- end client section -->

  <!-- contact section -->

  <section class="contact_section layout_padding">
    <div class="bg-img1">
      <img src="{% static 'images/bg-img-1.png' %}" alt="">
    </div>
    <div class="bg-img2">
      <img src="{% static 'images/bg-img-2.png' %}" alt="">
    </div>
    <div class="container">
      <div class="heading_container">
        <h2>
          Contact Us
        </h2>
      </div>
      <div class="">
        <div class="row">
          <div class="col-md-8 mx-auto">
            <form action="/createpost/ " method='POST'>
              {% csrf_token %}
              <div class="contact_form-container">
                <div>
                  <div>
                    <input type="text" placeholder="Name" name='name'>
                  </div>
                  <div>
                    <input type="text" placeholder="Phone Number" name='phone'>
                  </div>
                  <div>
                    <input type="email" placeholder="Email" name='email'>
                  </div>
                  <div class="">
                    <input type="text" placeholder="Message" class="message_input" name='message'>
                  </div>
                  <div class=" d-flex justify-content-center ">
                    <button type="submit">
                      Send
                    </button>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>


  <!-- end contact section -->


  <!-- info section -->
  <section class="info_section ">
    <div class="container">
      <div class="info_container">
        <div class="info_social">
          <div class="d-flex justify-content-center">
            <h4 class="">
              Follow on
            </h4>
          </div>
          <div class="social_box">
            <a href="">
              <img src="{% static 'images/fb.png' %}" alt="">
            </a>
            <a href="">
              <img src="{% static 'images/twitter.png' %}" alt="">
            </a>
            <a href="">
              <img src="{% static 'images/instagram.png' %}" alt="">
            </a>
            <a href="">
              <img src="{% static 'images/linkedin.png' %}" alt="">
            </a>
            <a href="">
              <img src="{% static 'images/dribble.png' %}" alt="">
            </a>
            <a href="">
              <img src="{% static 'images/pinterest.png' %}" alt="">
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end info_section -->

  <!-- footer section -->
  <section class="container-fluid footer_section">
    <div class="container">
      <p>
        &copy; 2019 All Rights Reserved By
        <a href="https://html.design/">Free Html Templates</a>
      </p>
    </div>
  </section>
  <!-- footer section -->

  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>

</body>

</html>